In [6]:

#%pip install numpy==1.23.5
# %pip install --upgrade gym
%pip install gymnasium
#import gym
import gymnasium as gym

# Load the FrozenLake environment
env = gym.make("FrozenLake-v1", is_slippery=False, render_mode="ansi")
state, info = env.reset()
print(env.render())

actions = [2, 2, 1, 1, 1, 2]  # Adjusted to navigate better
for step, action in enumerate(actions):
    new_state, reward, terminated, truncated, info = env.step(action)
    done = terminated or truncated

    print(f"Step {step + 1}:")
    print(f"Current State: {state}")
    print(f"Action Taken: {action}")
    print(f"New State: {new_state}")
    print(f"Reward: {reward}")
    print(f"Done: {done}")
    print(env.render())

    state = new_state
    if done:
        print("Episode finished.")
        break


Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.

SFFF
FHFH
FFFH
HFFG

Step 1:
Current State: 0
Action Taken: 2
New State: 1
Reward: 0.0
Done: False
  (Right)
SFFF
FHFH
FFFH
HFFG

Step 2:
Current State: 1
Action Taken: 2
New State: 2
Reward: 0.0
Done: False
  (Right)
SFFF
FHFH
FFFH
HFFG

Step 3:
Current State: 2
Action Taken: 1
New State: 6
Reward: 0.0
Done: False
  (Down)
SFFF
FHFH
FFFH
HFFG

Step 4:
Current State: 6
Action Taken: 1
New State: 10
Reward: 0.0
Done: False
  (Down)
SFFF
FHFH
FFFH
HFFG

Step 5:
Current State: 10
Action Taken: 1
New State: 14
Reward: 0.0
Done: False
  (Down)
SFFF
FHFH
FFFH
HFFG

Step 6:
Current State: 14
Action Taken: 2
New State: 15
Reward: 1.0
Done: True
  (Right)
SFFF
FHFH
FFFH
HFFG

Episode finished.


DEPRECATION: Loading egg at c:\program files\python312\lib\site-packages\vboxapi-1.0-py3.12.egg is deprecated. pip 24.3 will enforce this behaviour change. A possible replacement is to use pip for package installation.. Discussion can be found at https://github.com/pypa/pip/issues/12330

[notice] A new release of pip is available: 24.0 -> 25.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [8]:
#import gym
import numpy as np
import gymnasium as gym

# Create FrozenLake environment
env = gym.make("FrozenLake-v1", is_slippery=False)

# Initialize Q-table (states x actions)
Q = np.zeros((env.observation_space.n, env.action_space.n))

# Parameters
alpha = 0.8        # Learning rate
gamma = 0.95       # Discount factor
epsilon = 1.0      # Exploration rate
epsilon_decay = 0.99
episodes = 2000    # Number of training episodes

# Training loop
for episode in range(episodes):
    state, info = env.reset()
    done = False

    while not done:
        # Choose action (epsilon-greedy)
        if np.random.uniform(0, 1) < epsilon:
            action = env.action_space.sample()  # Explore
        else:
            action = np.argmax(Q[state, :])     # Exploit best known

        # Take action
        next_state, reward, terminated, truncated, info = env.step(action)
        done = terminated or truncated

        # Update Q-value
        Q[state, action] = Q[state, action] + alpha * (
            reward + gamma * np.max(Q[new_state, :]) - Q[state, action]
        )

        # Move to next state
        state = new_state

    # Decay exploration rate
    epsilon = max(0.01, epsilon * epsilon_decay)

print("Trained Q-table:")
print(Q)

# Test the trained agent
state, info = env.reset()
env.render()
done = False

while not done:
    action = np.argmax(Q[state, :])
    next_state, reward, terminated, truncated, info = env.step(action)
    done = terminated or truncated
    env.render()
    state = new_state

print("Final Reward:", reward)
env.close()


Trained Q-table:
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Final Reward: 0.0


C:\Users\visha\AppData\Roaming\Python\Python312\site-packages\gymnasium\envs\toy_text\frozen_lake.py:333: UserWarning: WARN: You are calling render method without specifying any render mode. You can specify the render_mode at initialization, e.g. gym.make("FrozenLake-v1", render_mode="rgb_array")
  gym.logger.warn(
